// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.entitlements-admin@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ENTITLEMENTS_ADMIN_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ENTITLEMENTS_ADMIN_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_entitlements_admin { () => { "{\"capability_id\":\"lenso.entitlements-admin@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"put_grant\",\"revoke_grant\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_entitlements_admin_client { () => { "{\"capability_id\":\"lenso.entitlements-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_entitlements_admin_client { () => { "{\"capability_id\":\"lenso.entitlements-admin@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const PUT_GRANT_OPERATION: &str = "put_grant";
pub const REVOKE_GRANT_OPERATION: &str = "revoke_grant";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PutGrantRequest {
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Option<Timestamp>,
    #[serde(rename = "feature")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub feature: String,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: Option<String>,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PutGrantResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "grant_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant_id: String,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PutGrantError {
    Forbidden,
    InvalidGrant,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeGrantRequest {
    #[serde(rename = "grant_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RevokeGrantResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RevokeGrantError {
    Forbidden,
    InvalidGrant,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct EntitlementsAdminPutGrant;
impl RequestCapability for EntitlementsAdminPutGrant {
    type Request = PutGrantRequest;
    type Response = PutGrantResponse;
    type DomainError = PutGrantError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PUT_GRANT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<EntitlementsAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).put_grant(context, request)
    }
}

#[derive(Debug)]
pub struct EntitlementsAdminRevokeGrant;
impl RequestCapability for EntitlementsAdminRevokeGrant {
    type Request = RevokeGrantRequest;
    type Response = RevokeGrantResponse;
    type DomainError = RevokeGrantError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != REVOKE_GRANT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<EntitlementsAdminRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).revoke_grant(context, request)
    }
}

impl serde::Serialize for PutGrantError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidGrant => serializer.serialize_str("invalid_grant"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PutGrantError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_grant" => Ok(Self::InvalidGrant),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RevokeGrantError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidGrant => serializer.serialize_str("invalid_grant"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RevokeGrantError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_grant" => Ok(Self::InvalidGrant),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_put_grant_request(value: &PutGrantRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_put_grant_request(wire: &str) -> Result<PutGrantRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_put_grant_response(value: &PutGrantResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_put_grant_response(wire: &str) -> Result<PutGrantResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_put_grant_error(value: &PutGrantError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_put_grant_error(wire: &str) -> Result<PutGrantError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_revoke_grant_request(value: &RevokeGrantRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_grant_request(wire: &str) -> Result<RevokeGrantRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_grant_response(value: &RevokeGrantResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_grant_response(wire: &str) -> Result<RevokeGrantResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_revoke_grant_error(value: &RevokeGrantError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_revoke_grant_error(wire: &str) -> Result<RevokeGrantError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoEntitlementsAdminPutGrantResult {
    fn __lenso_into_result(self) -> Result<Result<PutGrantResponse, PutGrantError>, RuntimeFailure>;
}
impl __LensoIntoEntitlementsAdminPutGrantResult for Result<PutGrantResponse, PutGrantError> {
    fn __lenso_into_result(self) -> Result<Result<PutGrantResponse, PutGrantError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoEntitlementsAdminPutGrantResult for Result<Result<PutGrantResponse, PutGrantError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<PutGrantResponse, PutGrantError>, RuntimeFailure> { self }
}
impl __LensoIntoEntitlementsAdminPutGrantResult for Result<PutGrantResponse, lenso_plugin_authoring::PluginError<PutGrantError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<PutGrantResponse, PutGrantError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoEntitlementsAdminPutGrantResult for Result<PutGrantResponse, EntitlementsAdminPutGrantInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<PutGrantResponse, PutGrantError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(EntitlementsAdminPutGrantInvocationError::Domain(error)) => Ok(Err(error)),
            Err(EntitlementsAdminPutGrantInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoEntitlementsAdminRevokeGrantResult {
    fn __lenso_into_result(self) -> Result<Result<RevokeGrantResponse, RevokeGrantError>, RuntimeFailure>;
}
impl __LensoIntoEntitlementsAdminRevokeGrantResult for Result<RevokeGrantResponse, RevokeGrantError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeGrantResponse, RevokeGrantError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoEntitlementsAdminRevokeGrantResult for Result<Result<RevokeGrantResponse, RevokeGrantError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RevokeGrantResponse, RevokeGrantError>, RuntimeFailure> { self }
}
impl __LensoIntoEntitlementsAdminRevokeGrantResult for Result<RevokeGrantResponse, lenso_plugin_authoring::PluginError<RevokeGrantError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RevokeGrantResponse, RevokeGrantError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoEntitlementsAdminRevokeGrantResult for Result<RevokeGrantResponse, EntitlementsAdminRevokeGrantInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RevokeGrantResponse, RevokeGrantError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(EntitlementsAdminRevokeGrantInvocationError::Domain(error)) => Ok(Err(error)),
            Err(EntitlementsAdminRevokeGrantInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait EntitlementsAdminProvider: fmt::Debug + 'static {
    fn put_grant(&self, context: InvocationContext, request: PutGrantRequest) -> NativeRequestFuture<EntitlementsAdminPutGrant>;
    fn revoke_grant(&self, context: InvocationContext, request: RevokeGrantRequest) -> NativeRequestFuture<EntitlementsAdminRevokeGrant>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_entitlements_admin {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportEntitlementsAdmin;
        impl $crate::EntitlementsAdminProvider for $plugin {
        fn put_grant(&self, context: __LensoNativeSupportEntitlementsAdmin::InvocationContext, request: $crate::PutGrantRequest) -> __LensoNativeSupportEntitlementsAdmin::NativeRequestFuture<$crate::EntitlementsAdminPutGrant> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::put_grant(&plugin, context, request).await;
                $crate::__LensoIntoEntitlementsAdminPutGrantResult::__lenso_into_result(result)
            })
        }
        fn revoke_grant(&self, context: __LensoNativeSupportEntitlementsAdmin::InvocationContext, request: $crate::RevokeGrantRequest) -> __LensoNativeSupportEntitlementsAdmin::NativeRequestFuture<$crate::EntitlementsAdminRevokeGrant> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::revoke_grant(&plugin, context, request).await;
                $crate::__LensoIntoEntitlementsAdminRevokeGrantResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct EntitlementsAdminRequestEndpoint { provider: Rc<dyn EntitlementsAdminProvider> }

#[derive(Debug)]
pub struct EntitlementsAdminEndpoint<P: EntitlementsAdminProvider> { provider: Rc<P>, request_endpoint: EntitlementsAdminRequestEndpoint }
impl<P: EntitlementsAdminProvider> EntitlementsAdminEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn EntitlementsAdminProvider> = provider.clone();
        Self { provider, request_endpoint: EntitlementsAdminRequestEndpoint { provider: request_provider } }
    }
}

impl<P: EntitlementsAdminProvider> NativeRequestEndpoint for EntitlementsAdminEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        PUT_GRANT_OPERATION,
        REVOKE_GRANT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            PUT_GRANT_OPERATION => {
                let Ok(request) = request.downcast::<PutGrantRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).put_grant(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            REVOKE_GRANT_OPERATION => {
                let Ok(request) = request.downcast::<RevokeGrantRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).revoke_grant(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_entitlements_admin {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::EntitlementsAdminEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_entitlements_admin {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_entitlements_admin!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct EntitlementsAdminClient {
    put_grant: NativeRequestHandle<EntitlementsAdminPutGrant>,
    revoke_grant: NativeRequestHandle<EntitlementsAdminRevokeGrant>,
}
impl EntitlementsAdminClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn put_grant(&self, request: PutGrantRequest) -> Result<PutGrantResponse, EntitlementsAdminPutGrantInvocationError> {
        self.put_grant.invoke(PUT_GRANT_OPERATION, request).await
            .map_err(EntitlementsAdminPutGrantInvocationError::Runtime)?
            .map_err(EntitlementsAdminPutGrantInvocationError::Domain)
    }

    pub async fn put_grant_with_context(&self, context: InvocationContext, request: PutGrantRequest) -> Result<PutGrantResponse, EntitlementsAdminPutGrantInvocationError> {
        self.put_grant.invoke_with_context(PUT_GRANT_OPERATION, context, request).await
            .map_err(EntitlementsAdminPutGrantInvocationError::Runtime)?
            .map_err(EntitlementsAdminPutGrantInvocationError::Domain)
    }

    pub async fn revoke_grant(&self, request: RevokeGrantRequest) -> Result<RevokeGrantResponse, EntitlementsAdminRevokeGrantInvocationError> {
        self.revoke_grant.invoke(REVOKE_GRANT_OPERATION, request).await
            .map_err(EntitlementsAdminRevokeGrantInvocationError::Runtime)?
            .map_err(EntitlementsAdminRevokeGrantInvocationError::Domain)
    }

    pub async fn revoke_grant_with_context(&self, context: InvocationContext, request: RevokeGrantRequest) -> Result<RevokeGrantResponse, EntitlementsAdminRevokeGrantInvocationError> {
        self.revoke_grant.invoke_with_context(REVOKE_GRANT_OPERATION, context, request).await
            .map_err(EntitlementsAdminRevokeGrantInvocationError::Runtime)?
            .map_err(EntitlementsAdminRevokeGrantInvocationError::Domain)
    }
}

impl CapabilityClient for EntitlementsAdminClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            put_grant: dependencies.one::<EntitlementsAdminPutGrant>()?,
            revoke_grant: dependencies.one::<EntitlementsAdminRevokeGrant>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for EntitlementsAdminClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    put_grant: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<EntitlementsAdminPutGrant>()?,
                    revoke_grant: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<EntitlementsAdminRevokeGrant>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum EntitlementsAdminPutGrantInvocationError {
    Domain(PutGrantError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum EntitlementsAdminRevokeGrantInvocationError {
    Domain(RevokeGrantError),
    Runtime(RuntimeFailure),
}
