// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.entitlements@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ENTITLEMENTS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ENTITLEMENTS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_entitlements { () => { "{\"capability_id\":\"lenso.entitlements@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"resolve_entitlement\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_entitlements_client { () => { "{\"capability_id\":\"lenso.entitlements@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_entitlements_client { () => { "{\"capability_id\":\"lenso.entitlements@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const RESOLVE_ENTITLEMENT_OPERATION: &str = "resolve_entitlement";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolveEntitlementRequest {
    #[serde(rename = "feature")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub feature: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResolveEntitlementResponse {
    #[serde(rename = "grant_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant_id: Option<String>,
    #[serde(rename = "granted")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub granted: bool,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: Option<String>,
    #[serde(rename = "policy_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy_revision: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ResolveEntitlementError {
    Forbidden,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Entitlements;
impl RequestCapability for Entitlements {
    type Request = ResolveEntitlementRequest;
    type Response = ResolveEntitlementResponse;
    type DomainError = ResolveEntitlementError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RESOLVE_ENTITLEMENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<EntitlementsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).resolve_entitlement(context, request)
    }
}

impl serde::Serialize for ResolveEntitlementError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ResolveEntitlementError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_resolve_entitlement_request(value: &ResolveEntitlementRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_entitlement_request(wire: &str) -> Result<ResolveEntitlementRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resolve_entitlement_response(value: &ResolveEntitlementResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_entitlement_response(wire: &str) -> Result<ResolveEntitlementResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_resolve_entitlement_error(value: &ResolveEntitlementError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_resolve_entitlement_error(wire: &str) -> Result<ResolveEntitlementError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoEntitlementsResolveEntitlementResult {
    fn __lenso_into_result(self) -> Result<Result<ResolveEntitlementResponse, ResolveEntitlementError>, RuntimeFailure>;
}
impl __LensoIntoEntitlementsResolveEntitlementResult for Result<ResolveEntitlementResponse, ResolveEntitlementError> {
    fn __lenso_into_result(self) -> Result<Result<ResolveEntitlementResponse, ResolveEntitlementError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoEntitlementsResolveEntitlementResult for Result<Result<ResolveEntitlementResponse, ResolveEntitlementError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ResolveEntitlementResponse, ResolveEntitlementError>, RuntimeFailure> { self }
}
impl __LensoIntoEntitlementsResolveEntitlementResult for Result<ResolveEntitlementResponse, lenso_plugin_authoring::PluginError<ResolveEntitlementError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ResolveEntitlementResponse, ResolveEntitlementError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoEntitlementsResolveEntitlementResult for Result<ResolveEntitlementResponse, EntitlementsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ResolveEntitlementResponse, ResolveEntitlementError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(EntitlementsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(EntitlementsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait EntitlementsProvider: fmt::Debug + 'static {
    fn resolve_entitlement(&self, context: InvocationContext, request: ResolveEntitlementRequest) -> NativeRequestFuture<Entitlements>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_entitlements {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportEntitlements;
        impl $crate::EntitlementsProvider for $plugin {
        fn resolve_entitlement(&self, context: __LensoNativeSupportEntitlements::InvocationContext, request: $crate::ResolveEntitlementRequest) -> __LensoNativeSupportEntitlements::NativeRequestFuture<$crate::Entitlements> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::resolve_entitlement(&plugin, context, request).await;
                $crate::__LensoIntoEntitlementsResolveEntitlementResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct EntitlementsRequestEndpoint { provider: Rc<dyn EntitlementsProvider> }

#[derive(Debug)]
pub struct EntitlementsEndpoint<P: EntitlementsProvider> { provider: Rc<P>, request_endpoint: EntitlementsRequestEndpoint }
impl<P: EntitlementsProvider> EntitlementsEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn EntitlementsProvider> = provider.clone();
        Self { provider, request_endpoint: EntitlementsRequestEndpoint { provider: request_provider } }
    }
}

impl<P: EntitlementsProvider> NativeRequestEndpoint for EntitlementsEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        RESOLVE_ENTITLEMENT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            RESOLVE_ENTITLEMENT_OPERATION => {
                let Ok(request) = request.downcast::<ResolveEntitlementRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).resolve_entitlement(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_entitlements {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::EntitlementsEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_entitlements {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_entitlements!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct EntitlementsClient {
    resolve_entitlement: NativeRequestHandle<Entitlements>,
}
impl EntitlementsClient {
    pub fn new(handle: NativeRequestHandle<Entitlements>) -> Self {
        Self { resolve_entitlement: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn resolve_entitlement(&self, request: ResolveEntitlementRequest) -> Result<ResolveEntitlementResponse, EntitlementsInvocationError> {
        self.resolve_entitlement.invoke(RESOLVE_ENTITLEMENT_OPERATION, request).await
            .map_err(EntitlementsInvocationError::Runtime)?
            .map_err(EntitlementsInvocationError::Domain)
    }

    pub async fn resolve_entitlement_with_context(&self, context: InvocationContext, request: ResolveEntitlementRequest) -> Result<ResolveEntitlementResponse, EntitlementsInvocationError> {
        self.resolve_entitlement.invoke_with_context(RESOLVE_ENTITLEMENT_OPERATION, context, request).await
            .map_err(EntitlementsInvocationError::Runtime)?
            .map_err(EntitlementsInvocationError::Domain)
    }
}

impl CapabilityClient for EntitlementsClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            resolve_entitlement: dependencies.one::<Entitlements>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for EntitlementsClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    resolve_entitlement: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Entitlements>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum EntitlementsInvocationError {
    Domain(ResolveEntitlementError),
    Runtime(RuntimeFailure),
}
